#Introduction to NumPy  

![alt text](https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/NumPy_logo.svg/1200px-NumPy_logo.svg.png)

NumPy (or Numpy) is a Linear Algebra Library for Python. NumPy is a Python package. It stands for 'Numerical Python'. It is a library consisting of multidimensional array objects and a collection of routines for processing of array.

Numpy is also incredibly fast, as it has bindings to C libraries.

## **About iPython Notebooks**

iPython Notebooks are interactive coding environments embedded in a webpage. You will be using iPython notebooks in this class. You only need to write code between the ### START CODE HERE ### and ### END CODE HERE ### comments. After writing your code, you can run the cell by either pressing "SHIFT"+"ENTER" or by clicking on "Run Cell" (denoted by a play symbol) in the left bar of the cell.


**In this notebook you will learn -**
* Numpy arrays
* Numpy Selecting and Indexing
* Numpy Operations

## Using NumPy

To import NumPy in Colaboratory simply type the following:


In [0]:
import numpy as np

# NumPy Indexing and Selection

In this section we will discuss how to select elements or groups of elements from an array.

In [0]:
import numpy as np

In [0]:
arr = np.arange(0,11)      

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [4]:
arr[8]      #Get a value at an index

8

In [5]:
arr[1:5]      #Get values in a range

array([1, 2, 3, 4])

In [6]:
arr[0:5]      #Get values in a range

array([0, 1, 2, 3, 4])

**Exercise 2.1:**

Create an array **arr** from 10 to 25 using **arange** function. Print the numbers from index 8 to 12.

In [8]:
### START CODE HERE ###
arr = np.arange(10,25)
arr[8:12]
  
### END CODE HERE ### 

array([18, 19, 20, 21])

**Expected Output:**

array([18, 19, 20, 21])

## Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [9]:
arr[0:5]=100      #Setting a value with index range (Broadcasting)

arr

array([100, 100, 100, 100, 100,  15,  16,  17,  18,  19,  20,  21,  22,
        23,  24])

In [10]:
# Reset array 
arr = np.arange(0,11)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
slice_of_arr = arr[0:6]

slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [12]:
slice_of_arr[:]=99

slice_of_arr

array([99, 99, 99, 99, 99, 99])

**Note:** The changes also occur in the original array.

In [13]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Data is not copied, it's a view of the original array. This avoids memory problems.

To get a copy of the array we can simply use the **copy** function.

In [14]:
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

**Exercise 2.2:**

Create an array **arr** from 5 to 15. Create a copy **arr2** of the same array and replace first 5 values with 100.

In [15]:
### START CODE HERE ###
arr = np.arange(5,15)
arr2 = arr.copy()
arr2[0:5] = 100
arr2
### END CODE HERE ### 

array([100, 100, 100, 100, 100,  10,  11,  12,  13,  14])

**Expected output:**

array([100, 100, 100, 100,   9,  10,  11,  12,  13,  14])

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**.

In [16]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [17]:
arr_2d[1]      #Indexing row


array([20, 25, 30])

In [18]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][0]

20

In [19]:
# Getting individual element value
arr_2d[1,0]

20

In [20]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [21]:
#Shape bottom row
arr_2d[2]

array([35, 40, 45])

In [22]:
#Shape bottom row
arr_2d[2,:]

array([35, 40, 45])

**Exercise 2.3:**

Using the given array **arr_2d** print (2, 2) matrix of the bottom right elements. 

In [23]:
### START CODE HERE ###
arr_2d      #don't forget to run the previous cells first

  
### END CODE HERE ### 

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

**Expected Output:**

array([[25, 30],

       [40, 45]])

### Fancy Indexing

Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array:

In [0]:
#Set up matrix
arr2d = np.zeros((10,10))

In [0]:
#Length of array
arr_length = arr2d.shape[1]

In [26]:
#Set up array

for i in range(arr_length):
    arr2d[i] = i
    
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

Fancy indexing allows the following

In [27]:
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [28]:
#Allows in any order
arr2d[[6,4,2,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

## Selection

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [29]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [0]:
bool_arr = arr>4

In [32]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [33]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [34]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

**Exercise 2.4:**

Create and array **odd** of odd numbers between 20 to 30 and print the array containing numbers greater than 25.

In [38]:
### START CODE HERE ###
odd = np.arange(21,30,2)
x = 25
odd = odd[odd>x]
odd
### END CODE HERE ### 

array([27, 29])

**Expected Output: **

array([27, 29])

# Great Job!
